#!/bin/sh
	objdump -W pg_snakeoil.so |\
	egrep -A3 DW_TAG_typedef |\
	perl -e ' while (<>) { chomp; @flds = split;next unless (1 < @flds);\
		next if $flds[0]  ne "DW_AT_name" && $flds[1] ne "DW_AT_name";\
		next if $flds[-1] =~ /^DW_FORM_str/;\
		print $flds[-1],"\n"; }'  |\
	sort | uniq > pg_snakeoil.typedefs

