#!/bin/sh

set -eux

# bytecode seems to be the last file retrieved
CLAMDB=/var/lib/clamav/bytecode.cvd

# start freshclam and wait for startup
if ! test -f $CLAMDB; then
	trap "service clamav-freshclam stop" 0 2 3 15
	service clamav-freshclam start
	C=0
	while ! test -f $CLAMDB; do
		sleep 5
		C=$((C + 1))
		test $C -gt 120 && exit 1
	done
fi

pg_buildext installcheck
