name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: sh

    strategy:
      matrix:
        pgversion:
          - 16
          - 15
          - 14
          - 13
          - 12
          - 11
          - 10

    env:
      PGVERSION: ${{ matrix.pgversion }}

    steps:
    - name: checkout
      uses: actions/checkout@v3

    - name: install pg
      run: |
        sudo apt-get install -y libclamav-dev
        sudo /usr/share/postgresql-common/pgdg/apt.postgresql.org.sh -v $PGVERSION -p -i
        sudo -u postgres createuser -s "$USER"
        chmod --verbose go+rx $HOME # drwxr-x--- runner docker /home/runner
        sudo pg_conftool $PGVERSION main set pg_snakeoil.signature_dir $PWD/testfiles
        sudo service postgresql restart # reload isn't enough for PGC_SU_BACKEND

    - name: build
      run: |
        make PROFILE="-Werror"
        sudo -E make install

    - name: test
      run: |
        make installcheck

    - name: show regression diffs
      if: ${{ failure() }}
      run: |
        cat regression.diffs
